Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,27 @@
 #!/usr/bin/env bash
 # This script transfers a file from our client to a server.
 
-if [ $# -lt 3 ]; then
-echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if [ $# -lt 4 ]
+then
+        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+        exit 1
+fi
+
+#assigiing paramental to variables
+
+path_to_files=$1
+ip=$2
+username=$3
+path_to_ssh_key-$4
+
+#disabbling
+
+scp -o "stricthostkeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# checking of the transfer was successful
+if [#? -eq 0]
+then
+	echo "FILE was transferd successfully"
 else
-scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
+	echo "file transfer failed"
+fi
